"use client";

import React from 'react';
import Link from 'next/link';
import { ArrowLeft, Scale, Shield, FileText } from 'lucide-react';

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <div className="flex items-center justify-between">
            <Link 
              href="/"
              className="inline-flex items-center text-gray-600 hover:text-gray-900 transition-colors"
            >
              <ArrowLeft className="h-5 w-5 mr-2" />
              Back to Home
            </Link>
            <div className="flex items-center space-x-2">
              <Scale className="h-6 w-6 text-purple-600" />
              <span className="text-lg font-semibold text-gray-900">Legal Documents</span>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
          {/* Header Section */}
          <div className="bg-gradient-to-r from-purple-600 to-pink-600 px-8 py-12 text-white">
            <div className="flex items-center space-x-4 mb-4">
              <div className="bg-white/20 rounded-lg p-3">
                <FileText className="h-8 w-8" />
              </div>
              <div>
                <h1 className="text-3xl font-bold">Terms and Conditions</h1>
                <p className="text-purple-100 mt-2">Last updated: January 2025</p>
              </div>
            </div>
          </div>

          {/* Content */}
          <div className="px-8 py-12">
            <div className="prose prose-gray max-w-none">
              
              {/* Section 1 */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center">
                  <span className="bg-purple-100 text-purple-600 rounded-full w-8 h-8 flex items-center justify-center text-sm font-bold mr-3">1</span>
                  Introduction and Acceptance
                </h2>
                <div className="bg-gray-50 p-6 rounded-lg">
                  <p className="text-gray-700 leading-relaxed">
                    By accessing or using Garnet AI's website, products, or services (collectively, the "Service"), you agree to be bound by these Terms and Conditions ("Terms"). If you do not agree with any part of these Terms, you must not use the Service. These Terms constitute a legally binding agreement between you (individually or on behalf of your company) and Garnet AI Limited, a company incorporated and registered in Ireland with its registered office at [Address], ("Garnet AI," "we," "us," or "our").
                  </p>
                </div>
              </section>

              {/* Section 2 */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center">
                  <span className="bg-purple-100 text-purple-600 rounded-full w-8 h-8 flex items-center justify-center text-sm font-bold mr-3">2</span>
                  Definitions
                </h2>
                <div className="space-y-4">
                  <div className="bg-blue-50 p-4 rounded-lg border-l-4 border-blue-400">
                    <p className="text-gray-700">
                      <strong>"User," "you," or "your"</strong> means any individual or entity accessing or using the Service.
                    </p>
                  </div>
                  <div className="bg-green-50 p-4 rounded-lg border-l-4 border-green-400">
                    <p className="text-gray-700">
                      <strong>"Content"</strong> refers to any text, data, information, graphics, code, or other materials provided by you to the Service or generated by the Service on your behalf.
                    </p>
                  </div>
                  <div className="bg-yellow-50 p-4 rounded-lg border-l-4 border-yellow-400">
                    <p className="text-gray-700">
                      <strong>"Subscription Plan"</strong> refers to any paid or free plan that grants access to certain features of the Service.
                    </p>
                  </div>
                </div>
              </section>

              {/* Section 3 */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center">
                  <span className="bg-purple-100 text-purple-600 rounded-full w-8 h-8 flex items-center justify-center text-sm font-bold mr-3">3</span>
                  Eligibility and Account Registration
                </h2>
                <div className="bg-gray-50 p-6 rounded-lg">
                  <p className="text-gray-700 leading-relaxed">
                    You must be at least 18 years old to use the Service. By registering for an account, you represent and warrant that you have the legal capacity to enter into these Terms and that all information you provide is accurate and complete. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account or any other breach of security.
                  </p>
                </div>
              </section>

              {/* Section 4 */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center">
                  <span className="bg-purple-100 text-purple-600 rounded-full w-8 h-8 flex items-center justify-center text-sm font-bold mr-3">4</span>
                  Use of the Service
                </h2>
                <div className="space-y-4">
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900 mb-2">4.1. License Grant</h3>
                    <div className="bg-green-50 p-4 rounded-lg">
                      <p className="text-gray-700">
                        Subject to these Terms and your compliance herewith, Garnet AI grants you a non-exclusive, non-transferable, revocable license to use the Service solely for your internal business purposes.
                      </p>
                    </div>
                  </div>
                  
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900 mb-2">4.2. User Conduct</h3>
                    <div className="bg-red-50 p-4 rounded-lg border-l-4 border-red-400">
                      <p className="text-gray-700 mb-3"><strong>You agree not to:</strong></p>
                      <ul className="space-y-2 text-gray-700">
                        <li className="flex items-start">
                          <span className="text-red-500 mr-2">•</span>
                          Use the Service for any unlawful purpose or in violation of applicable laws or regulations.
                        </li>
                        <li className="flex items-start">
                          <span className="text-red-500 mr-2">•</span>
                          Reverse engineer, decompile, or disassemble any portion of the Service.
                        </li>
                        <li className="flex items-start">
                          <span className="text-red-500 mr-2">•</span>
                          Impersonate any person or entity or falsely state or misrepresent your affiliation with any person or entity.
                        </li>
                        <li className="flex items-start">
                          <span className="text-red-500 mr-2">•</span>
                          Upload or transmit any malicious code, spam, or any material that infringes third-party intellectual property rights.
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </section>

              {/* Section 5 */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center">
                  <span className="bg-purple-100 text-purple-600 rounded-full w-8 h-8 flex items-center justify-center text-sm font-bold mr-3">5</span>
                  Intellectual Property Rights
                </h2>
                <div className="bg-gray-50 p-6 rounded-lg">
                  <p className="text-gray-700 leading-relaxed">
                    All intellectual property rights, including but not limited to copyrights, trademarks, trade secrets, patents, and other proprietary rights in and to the Service (including the software, content, user interface, and related documentation) are owned by Garnet AI or its licensors. You acknowledge and agree that except for the limited license expressly granted herein, no ownership or rights in the Service are transferred to you and that all goodwill associated therewith inures to Garnet AI's benefit.
                  </p>
                </div>
              </section>

              {/* Section 9 */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center">
                  <span className="bg-purple-100 text-purple-600 rounded-full w-8 h-8 flex items-center justify-center text-sm font-bold mr-3">9</span>
                  Disclaimers and Warranties
                </h2>
                <div className="space-y-4">
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900 mb-2">9.1. "As-Is" Service</h3>
                    <div className="bg-yellow-50 p-4 rounded-lg border-l-4 border-yellow-400">
                      <p className="text-gray-700 font-medium">
                        THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," AND GARNET AI DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
                      </p>
                    </div>
                  </div>
                  
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900 mb-2">9.2. No Warranty of Uninterrupted Service</h3>
                    <div className="bg-yellow-50 p-4 rounded-lg border-l-4 border-yellow-400">
                      <p className="text-gray-700 font-medium">
                        GARNET AI DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE.
                      </p>
                    </div>
                  </div>
                  
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900 mb-2">9.3. Accuracy of Results</h3>
                    <div className="bg-yellow-50 p-4 rounded-lg border-l-4 border-yellow-400">
                      <p className="text-gray-700 font-medium">
                        THE SERVICE UTILIZES ARTIFICIAL INTELLIGENCE MODELS AND THIRD-PARTY DATA SOURCES, AND THE RESULTS PROVIDED MAY NOT BE ACCURATE OR COMPLETE. GARNET AI MAKES NO REPRESENTATION OR WARRANTY REGARDING THE ACCURACY OR RELIABILITY OF ANY CONTENT OR DATA GENERATED OR ANALYZED BY THE SERVICE.
                      </p>
                    </div>
                  </div>
                </div>
              </section>

              {/* Section 10 */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center">
                  <span className="bg-purple-100 text-purple-600 rounded-full w-8 h-8 flex items-center justify-center text-sm font-bold mr-3">10</span>
                  Limitation of Liability
                </h2>
                <div className="bg-red-50 p-6 rounded-lg border-2 border-red-200">
                  <div className="flex items-start space-x-3">
                    <Shield className="h-6 w-6 text-red-500 mt-1 flex-shrink-0" />
                    <div>
                      <p className="text-gray-700 leading-relaxed mb-4 font-medium">
                        TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL GARNET AI, ITS AFFILIATES, LICENSORS, OR SERVICE PROVIDERS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES RESULTING FROM:
                      </p>
                      <ul className="space-y-2 text-gray-700 mb-4">
                        <li>(A) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE;</li>
                        <li>(B) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE;</li>
                        <li>(C) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT;</li>
                        <li>(D) ANY OTHER MATTER RELATING TO THE SERVICE, INCLUDING BUT NOT LIMITED TO ERRORS OR OMISSIONS IN THE SERVICE.</li>
                      </ul>
                      <p className="text-gray-700 leading-relaxed font-medium">
                        IN NO EVENT WILL GARNET AI'S AGGREGATE LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR YOUR USE OF THE SERVICE EXCEED THE TOTAL AMOUNT OF FEES PAID BY YOU TO GARNET AI IN THE SIX (6) MONTHS PRECEDING THE CLAIM. THE FOREGOING LIMITATIONS WILL APPLY EVEN IF GARNET AI HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND REGARDLESS OF THE THEORY OF LIABILITY.
                      </p>
                    </div>
                  </div>
                </div>
              </section>

              {/* Section 12 */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center">
                  <span className="bg-purple-100 text-purple-600 rounded-full w-8 h-8 flex items-center justify-center text-sm font-bold mr-3">12</span>
                  Governing Law and Dispute Resolution
                </h2>
                <div className="bg-blue-50 p-6 rounded-lg border-l-4 border-blue-400">
                  <p className="text-gray-700 leading-relaxed">
                    These Terms and any dispute arising out of or relating to these Terms or the Service will be governed by and construed in accordance with the laws of Ireland, without regard to conflict of law principles. Any dispute or claim arising out of or relating to these Terms or the Service will be resolved exclusively before the courts located in Dublin, Ireland, and you consent to the personal jurisdiction and venue of such courts.
                  </p>
                </div>
              </section>

              {/* Section 13 */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center">
                  <span className="bg-purple-100 text-purple-600 rounded-full w-8 h-8 flex items-center justify-center text-sm font-bold mr-3">13</span>
                  Modifications to Terms
                </h2>
                <div className="bg-gray-50 p-6 rounded-lg">
                  <p className="text-gray-700 leading-relaxed">
                    Garnet AI may modify these Terms from time to time. If material changes are made, Garnet AI will provide notice by posting the revised Terms and updating the "Last Updated" date at the top of these Terms. Your continued use of the Service after such modifications constitutes your acceptance of the revised Terms.
                  </p>
                </div>
              </section>

              {/* Section 14 */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center">
                  <span className="bg-purple-100 text-purple-600 rounded-full w-8 h-8 flex items-center justify-center text-sm font-bold mr-3">14</span>
                  Severability
                </h2>
                <div className="bg-gray-50 p-6 rounded-lg">
                  <p className="text-gray-700 leading-relaxed">
                    If any provision of these Terms is held to be invalid or unenforceable by a court of competent jurisdiction, that provision will be struck and the remaining provisions will remain in full force and effect.
                  </p>
                </div>
              </section>

              {/* Section 15 */}
              <section className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center">
                  <span className="bg-purple-100 text-purple-600 rounded-full w-8 h-8 flex items-center justify-center text-sm font-bold mr-3">15</span>
                  Entire Agreement
                </h2>
                <div className="bg-gray-50 p-6 rounded-lg">
                  <p className="text-gray-700 leading-relaxed">
                    These Terms, together with any Order Form(s), constitute the entire agreement between you and Garnet AI regarding the Service and supersede all prior and contemporaneous agreements, proposals, or representations, written or oral, concerning the Service.
                  </p>
                </div>
              </section>

            </div>

            {/* Contact Information */}
            <div className="mt-12 p-6 bg-gradient-to-r from-purple-50 to-pink-50 rounded-lg border border-purple-200">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Questions about these Terms?</h3>
              <p className="text-gray-700 mb-4">
                If you have any questions about these Terms and Conditions, please contact us:
              </p>
              <div className="space-y-2 text-gray-700">
                <p><strong>Email:</strong> rusha@garnetai.net</p>
                <p><strong>Company:</strong> Garnet AI Limited</p>
                <p><strong>Jurisdiction:</strong> Ireland</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
} 