[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # Note: For security, set actual database credentials in the Netlify UI Environment Variables section
  # The values below are placeholders and will be overridden by the UI settings
  DB_HOST = "localhost"
  DB_PORT = "5432"
  DB_NAME = "garnet_ai"
  DB_USER = "postgres"
  DB_PASSWORD = "placeholder"
  JWT_SECRET = "placeholder-jwt-secret-replace-in-netlify-ui"
  NEXT_PUBLIC_API_URL = "https://your-netlify-site-name.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Set up redirects for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Next.js API routes and Server Components need special handling
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  framework = "nextjs"

# IMPORTANT: In production, set the actual database credentials and JWT secret
# in the Netlify UI under Site settings > Build & deploy > Environment variables 