[build]
  base = "frontend"
  command = "npm run build:netlify"
  publish = ".next"
  functions = ".netlify/functions"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  # Add these environment variables for PostgreSQL
  POSTGRES_PRISMA_URL = "${env:DATABASE_URL}"
  POSTGRES_URL_NON_POOLING = "${env:DATABASE_URL}"
  
# Install required dependencies for pg and other modules
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle server-side dependencies
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Force installation of pg and other dependencies
[functions]
  included_files = ["node_modules/pg/**", "node_modules/bcryptjs/**", "node_modules/jose/**"]
  external_node_modules = ["pg", "bcryptjs", "jose"]
  node_bundler = "esbuild"

# Initialize database
[[redirects]]
  from = "/api/init-db"
  to = "/.netlify/functions/init-db"
  status = 200
  force = true

# Handle redirects for API routes
[[redirects]]
  from = "/api/auth/signup"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/api"
  status = 200
  force = true
  
# Default redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Add edge functions configuration for Netlify
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = false 