[build]
  base = "frontend"
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Redirect root to dashboard
[[redirects]]
  from = "/"
  to = "/dashboard"
  status = 302

# Handle SPA routing - catch all routes and serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 