[build]
  publish = "frontend/.next"
  command = "cd frontend && npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context]

  [context.production]

    [[context.production.headers]]
    for = "/_next/static/*"

      [context.production.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  [context.Dev-testing]

    [[context.Dev-testing.headers]]
    for = "/_next/static/*"

      [context.Dev-testing.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"