[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY = "true"

# Use Next.js runtime for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Database setup during build
[[plugins]]
  package = "@netlify/plugin-functions-core"

[[plugins.inputs.functions]]
  path = "netlify/functions/setup-db.js"
  schedule = "@build"

# API redirects to Netlify functions (fallback)
[[redirects]]
  from = "/api/answer"
  to = "/.netlify/functions/answer"
  status = 200

[[redirects]]
  from = "/api/ai/questionnaire"
  to = "/.netlify/functions/questionnaire"
  status = 200

[[redirects]]
  from = "/api/waitlist/signup"
  to = "/.netlify/functions/waitlist-signup"
  status = 200

# Handle SPA routing - catch all routes and serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 