[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "out"
  functions = "../netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  # Ensure all dependencies are installed
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  node_bundler = "esbuild"
  included_files = ["../netlify/functions/**"]

# Add the Netlify Functions Install Core plugin
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# API redirect for waitlist
[[redirects]]
  from = "/api/waitlist/*"
  to = "/.netlify/functions/waitlist-signup"
  status = 200

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[context]
  [context.production]
    command = "npm install && npm run build"

    [[context.production.headers]]
    for = "/_next/static/*"

      [context.production.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  [context.Dev-testing]
    command = "npm install && npm run build"

    [[context.Dev-testing.headers]]
    for = "/_next/static/*"

      [context.Dev-testing.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"