[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = ".next"
  functions = "../netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  node_bundler = "esbuild"
  included_files = ["../netlify/functions/**"]

# Add the Netlify Functions Install Core plugin
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/waitlist/*"
  to = "/.netlify/functions/waitlist-signup"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context]

  [context.production]

    [[context.production.headers]]
    for = "/_next/static/*"

      [context.production.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  [context.Dev-testing]

    [[context.Dev-testing.headers]]
    for = "/_next/static/*"

      [context.Dev-testing.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"