[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=frontend --include=dev"
  VITE_ALLOW_CJS_IMPORTS = "true"
  NETLIFY_USE_YARN = "false"
  NETLIFY_BUILD_INSTALL_PACKAGE_DEPS = "true"
  INSTALL_DEV_DEPS = "true"

[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 