[build]
  base = "frontend"
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/"
  to = "/dashboard"
  status = 302

[[redirects]]
  from = "/dashboard"
  to = "/dashboard/index.html"
  status = 200

[[redirects]]
  from = "/api/ai/questionnaire"
  to = "/.netlify/functions/questionnaire"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 