[build]
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "cd backend && npm install && npm run build && npm run start"
sleepApplication = false
multiRegionConfig = {"asia-southeast1-eqsg3a":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "5000" 