[build]
builder = "NIXPACKS"
rootDir = "backend"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npm run start"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "5000" 