[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "cd backend && npm run build && npm run start"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "5000" 