[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "5000"
# Set OPENAI_API_KEY in Railway UI dashboard 