[build]
builder = "NIXPACKS"
buildCommand = """
# 1) install root & workspace deps
npm install

# 2) install backend deps 
cd backend && npm install && npm run build
"""

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "cd backend && npm run start"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "5000" 