[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
runtime = "V2"
numReplicas = 1
sleepApplication = false
healthcheckPath = "/"
healthcheckTimeout = 300

[deploy.multiRegionConfig.asia-southeast1-eqsg3a]
numReplicas = 1

restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 