"use client";

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { MessageSquare, Send, RefreshCw, User, Bot } from 'lucide-react';
import Header from '@/components/Header';

// Prevent Next.js from expecting generateStaticParams()
export const dynamic = 'force-dynamic';

interface Question {
  id: string;
  text: string;
  answer?: string;
}

export default function ChatPage({ params }: { params: { id: string } }) {
  const router = useRouter();
  const [title, setTitle] = useState<string>('');
  const [questions, setQuestions] = useState<Question[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [userMessage, setUserMessage] = useState<string>('');

  useEffect(() => {
    const fetchQuestionnaire = async () => {
      setLoading(true);
      try {
        // Fetch questionnaire data
        const response = await fetch(`/api/questionnaires/${params.id}`);
        
        if (!response.ok) {
          throw new Error(`Failed to fetch questionnaire: ${response.status}`);
        }
        
        const data = await response.json();
        
        setTitle(data.title || 'Questionnaire');
        
        // Transform questions into the format we need
        const formattedQuestions = Array.isArray(data.questions) 
          ? data.questions.map((q: any) => ({
              id: q.id || crypto.randomUUID(),
              text: q.text || q.question || q,
              answer: q.answer || ''
            }))
          : [];
          
        setQuestions(formattedQuestions);
      } catch (err) {
        console.error('Error fetching questionnaire:', err);
        setError('Failed to load questionnaire. Please try again.');
      } finally {
        setLoading(false);
      }
    };

    if (params.id) {
      fetchQuestionnaire();
    }
  }, [params.id]);

  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!userMessage.trim()) return;
    
    // Add user message to questions array
    const newQuestion: Question = {
      id: crypto.randomUUID(),
      text: userMessage,
    };
    
    setQuestions([...questions, newQuestion]);
    setUserMessage('');
    
    // You could implement AI response generation here
    // For now, we'll just simulate a response
    setTimeout(() => {
      const aiResponse: Question = {
        id: crypto.randomUUID(),
        text: `I'm analyzing your question: "${userMessage}"`,
        answer: 'This is a placeholder response. In a real implementation, this would be generated by an AI.'
      };
      
      setQuestions(prev => [...prev, aiResponse]);
    }, 1000);
  };

  const handleBackToList = () => {
    router.push('/questionnaires');
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50">
        <Header />
        <main className="container mx-auto py-8 px-4">
          <div className="flex justify-center items-center h-64">
            <RefreshCw className="h-8 w-8 text-primary animate-spin" />
          </div>
        </main>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50">
        <Header />
        <main className="container mx-auto py-8 px-4">
          <div className="bg-white rounded-xl shadow-md p-6">
            <h1 className="text-xl font-bold text-red-600 mb-4">Error</h1>
            <p className="text-gray-700">{error}</p>
            <button
              onClick={handleBackToList}
              className="mt-4 garnet-button garnet-button-secondary"
            >
              Back to Questionnaires
            </button>
          </div>
        </main>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <Header />
      
      <main className="container mx-auto py-8 px-4">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-8">
          <div>
            <h1 className="text-2xl font-bold text-gray-800 flex items-center">
              <MessageSquare className="mr-3 h-7 w-7 text-primary" />
              {title}
            </h1>
            <p className="text-gray-600 mt-1">
              Chat with your questionnaire and get AI-powered assistance
            </p>
          </div>
          
          <button 
            className="garnet-button garnet-button-secondary flex items-center"
            onClick={handleBackToList}
          >
            Back to Questionnaires
          </button>
        </div>
        
        <div className="bg-white rounded-xl shadow-md flex flex-col h-[calc(100vh-200px)] max-h-[800px]">
          {/* Chat messages */}
          <div className="flex-grow overflow-y-auto p-6 space-y-4">
            {questions.length === 0 ? (
              <div className="text-center py-10">
                <MessageSquare className="h-12 w-12 text-gray-300 mx-auto mb-4" />
                <p className="text-gray-500">No messages yet. Start the conversation by sending a message below.</p>
              </div>
            ) : (
              questions.map((question) => (
                <div key={question.id} className="space-y-3">
                  <div className="flex items-start gap-3">
                    <div className="w-8 h-8 rounded-full bg-primary text-white flex items-center justify-center flex-shrink-0">
                      <User className="h-4 w-4" />
                    </div>
                    <div className="bg-gray-100 rounded-lg p-3 max-w-[80%]">
                      <p className="text-gray-800">{question.text}</p>
                    </div>
                  </div>
                  
                  {question.answer && (
                    <div className="flex items-start gap-3 ml-auto flex-row-reverse">
                      <div className="w-8 h-8 rounded-full bg-secondary text-white flex items-center justify-center flex-shrink-0">
                        <Bot className="h-4 w-4" />
                      </div>
                      <div className="bg-secondary/10 rounded-lg p-3 max-w-[80%]">
                        <p className="text-gray-800">{question.answer}</p>
                      </div>
                    </div>
                  )}
                </div>
              ))
            )}
          </div>
          
          {/* Input area */}
          <div className="border-t border-gray-200 p-4">
            <form onSubmit={handleSendMessage} className="flex gap-2">
              <input
                type="text"
                className="garnet-input flex-grow"
                placeholder="Type your message here..."
                value={userMessage}
                onChange={(e) => setUserMessage(e.target.value)}
              />
              <button 
                type="submit"
                className="garnet-button garnet-button-gradient"
                disabled={!userMessage.trim()}
              >
                <Send className="h-5 w-5" />
              </button>
            </form>
          </div>
        </div>
      </main>
    </div>
  );
} 