name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Frontend setup
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      # Backend setup
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      # Run unit tests
      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test
      
      # Run accessibility tests
      - name: Run Accessibility Tests
        working-directory: ./frontend
        run: |
          npx jest --config=jest.config.accessibility.js
          
      # Visual regression tests with Percy
      - name: Run Visual Regression Tests
        working-directory: ./frontend
        run: npx percy snapshot --config=percy.config.js
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      
      # ESLint
      - name: Run Frontend Linting
        working-directory: ./frontend
        run: npm run lint
        
      - name: Run Backend Linting
        working-directory: ./backend
        run: npm run lint

      - name: Success Message
        run: echo "✅ CI completed successfully for both frontend and backend!"